### ISSUE TITLE
Is there a reason for making your own delayms wrapper?

### ISSUE THREAD

**Issue by 257m** [Matiasus/st7735#26]
This isn't a real issue but I was just curious. When I remove the function and just use _delay_ms directly it doesn't seem to work which is rather strange. Is it for extra delay?

**Comment by Matiasus** [comment]
Hi, It was written because there is necessary used variable time delay function.

**Comment by 257m** [comment]
I mean why not just do _delay_ms(time)?

**Comment by Matiasus** [comment]
Hi, as I wrote before it was written because there is necessary used variable time delay function. Argument of delay_ms() function can be only constant and passing variable time delay argument from const uint8_t INIT_ST7735B[] PROGMEM array to _delay_ms() function reports an error ([interesting link](https://www.avrfreaks.net/s/topic/a5C3l000000UbihEAC/t158787?comment=P-1273985)). I haven't found a better solution, but I'll be glad if you have any improvements.

**Comment by 257m** [comment]
> Hi, as I wrote before it was written because there is necessary used variable time delay function. Argument of delay_ms() function can be only constant and passing variable time delay argument from const uint8_t INIT_ST7735B[] PROGMEM array to _delay_ms() function reports an error ([interesting link](https://www.avrfreaks.net/s/topic/a5C3l000000UbihEAC/t158787?comment=P-1273985)). I haven't found a better solution, but I'll be glad if you have any improvements.

Oh that's interesting. Weird that the argument is const. I had a custom implementation of delay_ms that didn't have it as const so I didn't notice the error. When removing the loop it still didn't work for some reason. Might just be my delay_ms is broken. I guess the loop is a lot easier than writing a custom one. Thanks for your time.
